apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-paygate-istio-system
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: paygate-istio-system
