spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
#              memory: 256Mi
            limits:
              cpu: "1.0"
#              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: SERVICE_PORT
            value: "8080"
          - name: CUST_PROFILE_HOST
            value: "accountprofile"
          - name: CUST_PROFILE_PORT
            value: "8080"
          - name: ACC_SERVICE_HOST
            value: "accountservice"
          - name: ACC_SERVICE_PORT
            value: "8080"
