{
 "title": "Payment Gateway Overview",
 "tags": [ "payment-gateway" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "project", "label": "Namespace", "query": "${VAR_PROJECT}" }
  ]
 },
 "panels": [
  {
   "title": "Services Up",
   "type": "singlestat",
   "description": "Service Running in Payment Gateway",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$project\"})"
    }
   ]
  },
  {
   "title": "Camel Exchange Completed",
   "type": "singlestat",
   "description": "Total Camel Exchanged Completed",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{kubernetes_namespace=\"$project\"})"
    }
   ]
  },
  {
   "title": "Camel Exchange Failed",
   "type": "singlestat",
   "description": "Total Camel Exchanged Failed",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{kubernetes_namespace=\"$project\"})"
    }
   ]
  },
  {
   "title": "Total Camel Exchange",
   "type": "singlestat",
   "description": "Total Camel Exchanged Processed",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{kubernetes_namespace=\"$project\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage for all services under Payment Gateway",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# NodeJs and Kafka\nlabel_join(rate({__name__=~\".*process_cpu_seconds_total\", kubernetes_namespace=\"$project\"}[1m]), \"__name__\", \"\", \"app\", \"strimzi_io_name\")",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "# SpringBoot\nrate(system_cpu_usage{namespace=\"$project\"}[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "JVM / Heap Memory Usage",
   "type": "graph",
   "description": "JVM or Heap Memory Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_namespace=\"$project\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    },
    {
     "expr": "{__name__=~\".*:nodejs_heap_size_used_bytes\", kubernetes_namespace=\"$project\"}",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=\"$project\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "SpringBoot Average Response Time",
   "type": "graph",
   "description": "SpringBoot applications average response time for business requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{uri=~\"/ws/pg/.*\", kubernetes_namespace=\"$project\"} / http_server_requests_seconds_count {uri=~\"/ws/pg/.*\", kubernetes_namespace=\"$project\"}",
     "legendFormat": "{{app}}{{uri}}"
    }
   ]
  },
  {
   "title": "NodeJs Average Response Time",
   "type": "graph",
   "description": "NodeJs applications average response time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_duration_sum\", kubernetes_namespace=\"$project\"} / {__name__=~\".*_duration_count\", kubernetes_namespace=\"$project\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}