{
 "title": "Payment Gateway Overview",
 "tags": [ "payment-gateway" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "paygate" },
   { "name": "kafka_cluster", "label": "Kafka Cluster", "query": "kafka-cluster" }
  ]
 },
 "panels": [
  {
   "title": "Services Up",
   "type": "singlestat",
   "description": "Service Running in Payment Gateway",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Kafka Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$namespace\",strimzi_io_cluster=\"$kafka_cluster\"})"
    },
    {}
   ]
  },
  {
   "title": "Online Kafka Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{kubernetes_namespace=\"$namespace\",strimzi_io_cluster=\"$kafka_cluster\"})"
    }
   ]
  },
  {
   "title": "# Kafka Connector",
   "type": "singlestat",
   "description": "Number of Kafka Connectors",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{strimzi_io_kind=~\"KafkaConnect.*\", kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Zookeeper Quorum Size",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(zookeeper_quorumsize{kubernetes_namespace=\"$namespace\",strimzi_io_cluster=\"$kafka_cluster\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Total Camel Exchange",
   "type": "singlestat",
   "description": "Total Camel Exchanged Processed",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesTotal{kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Camel Exchange Completed",
   "type": "singlestat",
   "description": "Total Camel Exchanged Completed",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesCompleted{kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Camel Exchange Failed",
   "type": "singlestat",
   "description": "Total Camel Exchanged Failed",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{kubernetes_namespace=\"$namespace\",strimzi_io_cluster=\"$kafka_cluster\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage for all services under Payment Gateway",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# NodeJs and Kafka\nlabel_join(rate({__name__=~\".*process_cpu_seconds_total\", kubernetes_namespace=\"$namespace\"}[1m]), \"__name__\", \"\", \"app\", \"strimzi_io_name\")",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "# SpringBoot\nrate(system_cpu_usage{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "JVM / Heap Memory Usage",
   "type": "graph",
   "description": "JVM or Heap Memory Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    },
    {
     "expr": "{__name__=~\".*:nodejs_heap_size_used_bytes\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=\"$namespace\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "SpringBoot Average Response Time",
   "type": "graph",
   "description": "SpringBoot applications average response time for business requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{uri=~\"/ws/pg/.*\", kubernetes_namespace=\"$namespace\"} / http_server_requests_seconds_count {uri=~\"/ws/pg/.*\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}}{{uri}}"
    }
   ]
  },
  {
   "title": "NodeJs Average Response Time",
   "type": "graph",
   "description": "NodeJs applications average response time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_duration_sum\", kubernetes_namespace=\"$namespace\"} / {__name__=~\".*_duration_count\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}