{
 "title": "Strimzi Kafka",
 "tags": [
  "Strimzi",
  "Kafka",
  "Payment Gateway"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_server_replicamanager_leadercount)"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$kubernetes_namespace\"})"
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": "query_result(kafka_cluster_partition_replicascount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": "query_result(kafka_log_log_size{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\"})"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelections_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "singlestat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "singlestat",
   "description": "Number of In-Sync Replicas for this Topic/Partition",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{topic=~\"$kafka_topic\"})"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate",
   "type": "singlestat",
   "description": "Total Produce Request Rate",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Incoming Byte Rate",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "singlestat",
   "description": "Total Outgoing Byte Rate",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic Partitions",
   "type": "singlestat",
   "description": "Total number of partitions for this Topic",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$kafka_topic\"})"
    }
   ]
  },
  {
   "title": "Topic Replicas",
   "type": "singlestat",
   "description": "Number of Replicas for this Topic/Partition",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{topic=~\"$kafka_topic\"})"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate",
   "type": "singlestat",
   "description": "Incoming Messages Rate",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "format": "wps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Topic partitions under replicated partitions",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{topic=~\"$kafka_topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions at Minimum ISR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{topic=~\"$kafka_topic\"})"
    }
   ]
  },
  { "title": "Kafka Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Messages consumed per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=~\"$kafka_topic\"}[1m])/60) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$kafka_topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "  sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidle_percent{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_log_log_size{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",partition=~\"$kafka_partition\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 68 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(zookeeper_quorumsize{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 68 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\", strimzi_io_name=\"$strimzi_cluster_name-zookeeper-client\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_name=\"$strimzi_cluster_name-zookeeper-client\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Connnect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Kafka Connector",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{kubernetes_namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"})"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count{kubernetes_namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"})"
    }
   ]
  },
  {
   "title": "Incoming Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_metrics_connect_1_incoming_byte_rate{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_metrics_connect_1_outgoing_byte_rate{kubernetes_namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_kind=~\"KafkaConnect.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$kubernetes_namespace\", strimzi_io_kind=~\"KafkaConnect.*\"}[5m]))"
    }
   ]
  },
  { "title": "Partitions and Offsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Number of Partitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$kafka_topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Order Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{topic=~\"$kafka_topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=~\"$kafka_topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Lag By Consumer Group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$kafka_topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$kafka_topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{topic=~\"$kafka_topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}