apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: paygate-springboot-metrics
  labels:
    app: paygate
spec:
  selector:
    matchLabels:
      paygate/kind: springboot
  namespaceSelector:
    matchNames:
      - paygate-apps
  podMetricsEndpoints:
  - path: /actuator/prometheus
    port: http