# oc create secret generic alertmanager-alertmanager --from-file=alertmanager.yaml=alert-manager-config.yaml
global:
  slack_api_url: https://ssa-mr19696.slack.com
route:
  receiver: slack
receivers:
- name: slack
  slack_configs:
  - channel: "#paygate-strimzi"
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    send_resolved: true
