== Account Service
This as part of Payment Gateway Demo services. It requires a MongoDB deployment to store the account balance information.

=== To Deploy and Run on Openshift

1. Clone this git onto your computer. Modify the the src/main/java/resources/applcation.properties with the following value:

spring.profiles.active=ocp

2. In the project folder, run the following oc command to create the application and mongodb.
oc new-app -f templates/deployment-templates.yaml

=== To run as standalone apps, please ensure that you have 

1. Clone this git onto your computer. Modify the the src/main/java/resources/applcation.properties with the following value:

spring.profiles.active=dev

Make sure the mongodb properties in src/main/java/resources/application-dev.properties are correct configured according to your environment:

+
[source,bash]
----
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=balance
spring.data.mongodb.password=balance
spring.data.mongodb.database=balance
----

2. Run the following maven command in the project folder to start the SpringBoot apps:
mvn spring-boot:run 